[SYCLomatic #367] modify autocomplete case for easy adding option.
oneapi-src/SYCLomatic-test pull request #143
Opened 2022-11-30 03:02 UTC by tangjj11

Signed-off-by: Tang, Jiajun jiajun.tang@intel.com

2022-11-30 03:15 UTC, tangjj11 commented
modify this case just because when we add a new DPCT option, this test must be failed, If we adjust this case firstly, all of other PR except the adding option PR will run failed of this case. So I change this case into substring match and add a corresponding full string match case to lit test.

2022-12-05 09:46 UTC, wenhuiNi commented
maybe you need add SYCLomatic PR num.
you can refer to https://github.com/oneapi-src/SYCLomatic-test/pull/126

2022-12-06 05:26 UTC, zhiweij1 approved these changes

2022-12-06 05:40 UTC, ShengchenJ requested changes
Please refine the code, add for the iterate the each option?

2022-12-08 01:12 UTC, tomflinda approved these changes

2022-12-08 01:31 UTC, ShengchenJ approved these changes

2022-12-08 01:32 UTC, merged