[SYCLomatic #524] Add test for cub::DeviceReduce::Min/Max
oneapi-src/SYCLomatic-test pull request #207
Opened 2023-01-31 03:26 UTC by yihanwg

Signed-off-by: Wang, Yihan <yihan.wang@intel.com>

2023-02-13 02:12 UTC, tangjj11 approved these changes

2023-02-13 12:07 UTC, ShengchenJ requested changes

2023-02-13 12:07 UTC, ShengchenJ commented on features/feature_case/cub/cub_device_reduce_max.cu
> +// ====------ cub_device_reduce_min.cu-------------------- *- CUDA -* ------===//
The comment looks duplicated.

2023-02-14 01:37 UTC, yihanwg commented on features/feature_case/cub/cub_device_reduce_max.cu
> +// ====------ cub_device_reduce_min.cu-------------------- *- CUDA -* ------===//
removed.

2023-02-16 06:55 UTC, ShengchenJ reviewed
How about merge the min and max implement into one end-to-end case?

2023-02-22 07:22 UTC, yihanwg commented
> How about merge the min and max implement into one end-to-end case?

I will add argmin/argmax e2e test later, separate tests make it easier to find test failures, what do you think about?

2023-02-28 07:03 UTC, zhimingwang36 approved these changes
LGTM

2023-02-28 07:04 UTC, merged