[SYCLomatic] Testing zero allocation and fix expected comments
oneapi-src/SYCLomatic-test pull request #234
Opened 2023-02-17 18:16 UTC by danhoeflinger

Adding a test of a size zero vector.  Will throw exception until https://github.com/oneapi-src/SYCLomatic/pull/619 is merged.

Fixing some incorrect comments describing expected values for `_Verbose` output.

2023-02-22 05:54 UTC, zhimingwang36 approved these changes
LGTM

2023-02-22 05:55 UTC, zhimingwang36 requested changes
Seem this test case failed.

2023-02-22 17:49 UTC, danhoeflinger commented
> Seem this test case failed.

I believe this is an unrelated failure in `onedpl_test_copy_if.cpp`.  I'm not sure why it hasn't complained in the past, but I believe I have resolved it in #240.

2023-03-27 17:02 UTC, timmiesmith commented
@zhimingwang36 would you please confirm #243 resolved the test failure and this PR can be re-approved and merged?

2023-06-29 00:14 UTC, zhimingwang36 approved these changes
LGTM

2023-06-29 00:15 UTC, merged