[SYCLomatic #878] Add test case for migration of thrust::equal_range
oneapi-src/SYCLomatic-test pull request #313
Opened 2023-05-04 02:07 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2023-05-18 00:17 UTC, zhiweij1 requested changes

2023-05-18 00:17 UTC, zhiweij1 commented on features/feature_case/thrust/thrust_equal_range.cu
> +// -------------------===//
```suggestion
```

2023-05-18 00:21 UTC, tomflinda commented on features/feature_case/thrust/thrust_equal_range.cu
> +// -------------------===//
will update in the updated PR.

2023-05-18 00:26 UTC, zhiweij1 approved these changes

2023-05-23 05:04 UTC, ShengchenJ approved these changes

2023-05-23 05:05 UTC, merged