[SYCLomtaic-test]Enable cuda backend for features and help-function
oneapi-src/SYCLomatic-test pull request #325
Opened 2023-05-16 01:41 UTC by wenhuiNi

2023-05-18 03:24 UTC, yihanwg commented on option_mapping.json
> +        "option_cuda" : ""
Add new line

2023-05-18 03:28 UTC, tangjj11 requested changes

2023-05-18 03:28 UTC, tangjj11 commented on README.md
> +| "option_cuda" : ""                        | a. c2s migrates with default opt. b. The test run on the CPU device. |
why CPU?

2023-05-18 03:28 UTC, tangjj11 commented on option_mapping.json
> +        "option_cuda" : ""
redundant spaces before `:`

2023-05-18 03:28 UTC, tangjj11 commented on run_test.py
> +def main():
redundant spaces after `:`

2023-05-18 05:18 UTC, ShengchenJ requested changes

2023-05-18 05:18 UTC, ShengchenJ commented on README.md
> +| "option_cuda" : ""                        | a. c2s migrates with default opt. b. The test run on the CPU device. |
Should on the NV backend.

2023-05-18 07:00 UTC, tangjj11 approved these changes

2023-05-23 05:11 UTC, ShengchenJ approved these changes

2023-05-23 05:14 UTC, merged