[SYCLomatic #933] Add test case for multiple definition of dpct::exce ption_handler
oneapi-src/SYCLomatic-test pull request #343
Opened 2023-05-29 01:13 UTC by tomflinda

Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

2023-05-29 01:24 UTC, zhiweij1 requested changes

2023-05-29 01:24 UTC, zhiweij1 commented on help_function/src/multi_definition_test/multi_definition_test.py
> +# ====------ rodinia.py---------- *- Python -* ----===##
```suggestion
# ===------ multi_definition_test.py --------------------- *- Python -* ----===#
```

2023-05-29 01:26 UTC, tomflinda commented on help_function/src/multi_definition_test/multi_definition_test.py
> +# ====------ rodinia.py---------- *- Python -* ----===##
will update it in the updated PR.

2023-05-29 01:29 UTC, zhiweij1 approved these changes

2023-07-11 07:29 UTC, ShengchenJ approved these changes

2023-07-11 07:41 UTC, ShengchenJ approved these changes

2023-07-11 07:41 UTC, merged