Separate some test cases that need to be tested on the cuda backend
oneapi-src/SYCLomatic-test pull request #350
Opened 2023-05-31 06:59 UTC by wenhuiNi

2023-06-15 00:54 UTC, yihanwg commented on features/config/TEMPLATE_complex.xml
>  </test>
New line

2023-06-15 00:55 UTC, yihanwg approved these changes

2023-06-15 00:56 UTC, tangjj11 requested changes

2023-06-15 00:56 UTC, tangjj11 commented on help_function/help_function.xml
> +    <test testName="array_copy" configFile="config/TEMPLATE_help_function_eanble_cuda_backend.xml" />
```suggestion
    <test testName="array_copy" configFile="config/TEMPLATE_help_function_enable_cuda_backend.xml" />
```

2023-06-15 01:31 UTC, tangjj11 approved these changes

2023-06-19 08:14 UTC, ShengchenJ requested changes

2023-06-19 08:14 UTC, ShengchenJ commented on help_function/help_function.xml
> +    <test testName="assign_device_vector" configFile="config/TEMPLATE_help_function_enable_cuda_backend.xml" />
Please keep the help function configuration xml. And skip the CUDA backend if needed.

2023-06-19 08:14 UTC, ShengchenJ commented on run_test.py
> +
Please remove the no need space.

2023-06-20 01:17 UTC, ShengchenJ approved these changes

2023-06-26 01:40 UTC, zhimingwang36 commented on help_function/config/image_wrapper.xml
> +      <optlevelRule excludeOptlevelNameString="cuda" />
### 
```suggestion
      <optlevelRule excludeOptlevelNameString="cuda-backend" />
```

2023-07-04 01:46 UTC, zhimingwang36 approved these changes
LGTM

2023-07-04 01:47 UTC, merged